__title__ = 'pegass_auth'
__description__ = 'pegass_auth is a tiny client tool to help you make some HTTP request on Pegass'
__url__ = 'https://github.com/Annouar/pegass_auth'
__version__ = '1.0.2'
__author__ = 'Annouar'
__license__ = 'MIT'
